const constants = {
    ADD_FAV: "ADD_FAV",
    REMOVE_FAV: "REMOVE_FAV",
    SET_TOTAL: "SET_TOTAL",
    CHANGE_RESULT: "ADD_RESULT",
    SHOW_NAV_BAR: "SHOW_NAV_BAR",
    GENERAL_QUERY: "GENERAL_QUERY",
    ADVANCED_QUERY_PARAMS: "ADVANCED_QUERY_PARAMS",
    QUERY_PHONE_NUM_CHANGE: "QUERY_PHONE_NUM_CHANGE"
}

export default constants
