const constants = {
    ADD_FAV: "ADD_FAV",
    REMOVE_FAV: "REMOVE_FAV",
    CHANGE_RESULT: "CHANGE_RESULT",
    CHANGE_CURR_PAGE: "CHANGE_CURR_PAGE",
    CHANGE_QUERY_PARAMS: "CHANGE_QUERY_PARAMS",
    FETCHING: "FETCHING",
    CANCLE_FETCHING: "CANCLE_FETCHING",
    GENERAL_QUERY: "GENERAL_QUERY"
}

export default constants
