const constants = {
    ADD_FAV: "ADD_FAV",
    REMOVE_FAV: "REMOVE_FAV",
    CHANGE_RESULT: "CHANGE_RESULT",
    CHANGE_CURR_PAGE: "CHANGE_CURR_PAGE",
    CHANGE_QUERY_PARAMS: "CHANGE_QUERY_PARAMS",
    SHOW_NAV_BAR: "SHOW_NAV_BAR",
    START_QUERYING: "START_QUERYING",
    CANCLE_QUERYING: "CANCLE_QUERYING",
    GENERAL_QUERY: "GENERAL_QUERY",
    ADVANCED_QUERY_PARAMS: "ADVANCED_QUERY_PARAMS",
    QUERY_PHONE_NUM_CHANGE: "QUERY_PHONE_NUM_CHANGE"
}

export default constants
